language: node_js

jobs:
    include:
      os:
        - osx
      os:
        - linux 
          arch: arm64
          dist: bionic
      os:
        - linux 
          arch: arm64
          dist: xenial

node_js:
  - 12.14.1

cahce: npm

script:
  - npm clean

install:
  - npm install

script:
  - npm test
  - npm run coverage
  - npm run build
  - npm run stats