language: node_js

os:
    - linux
    - osx

node_js:
    - 12.14.1

cache: nmp

before_install:
    - npm clean

install:
    - npm install

after_install:
    - npm test
    - npm run coverage
    - npm run build
    - npm run stats
