language: node_js

os:
    - linux
    - osx
    - windows
    - linux arch: arm64 dist: bionic
    - linux arch: arm64 dist: bionic

node_js:
  - 12.14.1

cahce: npm

script:
  - npm clean

install:
  - npm install

script:
  - npm test
  - npm run coverage
  - npm run build
  - npm run stats