language: node_js

os: linux
dist: xenial

os:
  -osx

node_js:
  - 12.14.1

cahce: npm

script:
  - npm clean

install:
  - npm install

script:
  - npm test
  - npm run coverage
  - npm run build
  - npm run stats